name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build bfbc2-master-server
      run: docker build -t bfbc2-master-server:$(date +%s) ./master-server
    - name: Build bfbc2-server
      run: docker build -t bfbc2-server:$(date +%s) ./game-server
